services:
  - type: web
    name: pay3-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: WEB_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SMART_ACCOUNT_ENCRYPTION_KEY
        sync: false
      - key: STELLAR_NETWORK_PASSPHRASE
        value: "Test SDF Network ; September 2015"
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
